# model path
model_path: "model/best.pt"

# true:use gpu, false:use cpu
use_gpu_capture: false

# the screnn region to capture
screen_region:
  left: 0
  top: 10
  width: 1280
  height: 800

# class names
names: ['tank']

# classes to detect
aim_classes: [0,]

# prefer heads, then body
preferred_cls: [1]

# mouse move delay(0 means no delay)
mouse_move_delay: 0.01

# min conf, if the confidence of the detection is less than this value, it will not be considered
confidence_threshold: 0.4

# visualize or not(true for debug)
visualize: true

# path to log file
log_file: "log/run.log"